### ISSUE TITLE
Interpolation doesn't seem to work

### ISSUE THREAD

**Issue by dmihalcik** [dmihalcik/viper-toolkit#6]
When interpolating polygons, I get an exception of the form:

```
    at viper.api.impl.AttributeImpl.aggregateSetAttrValueAtSpan(AttributeImpl.java:867)
    at edu.umd.cfar.lamp.viper.gui.core.PropagateInterpolateImpl.helpInterpolateAttribute(PropagateInterpolateImpl.java:312)
    at edu.umd.cfar.lamp.viper.gui.core.PropagateInterpolateImpl.interpolateDescriptors(PropagateInterpolateImpl.java:532)
    at edu.umd.cfar.lamp.viper.gui.table.AbstractViperTable$DescPropPopup$InterpToMarkAction.actionPerformed(AbstractViperTable.java:383)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1223)
    at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:137)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1264)
    at java.awt.Component.processMouseEvent(Component.java:6348)
```

**Comment by dmihalcik** [comment]
This could be fixed by replacing edu.umd.cfar.lamp.viper.gui.core.PropagateInterpolateImpl's interpolateDescriptors(...) method with:

```
public void interpolateDescriptors(final Iterator descs,
        final Instant start, final Instant stop) {
            Span newSpan = startStop2Interval(start, stop);
            while (descs.hasNext()) {
                Descriptor d = (Descriptor) descs.next();
                InstantRange newDescriptorRange = d.getValidRange();
                if (mediator.getHiders().getDescriptorVisibility(d) > NodeVisibilityManager.RANGE_LOCKED) {
                    Iterator selectedRange = Collections.singleton(newSpan).iterator();
                    if (mediator.getChronicleSelectionModel() != null) {
                        if (mediator.getChronicleSelectionModel().getSelectedTime() != null) {
                            selectedRange = mediator.getChronicleSelectionModel().getSelectedTime().iterator(newSpan);
                        }
                    }
                    if (!newDescriptorRange.contains(newSpan)) {
                        while(selectedRange.hasNext()) {
                            newDescriptorRange.add(selectedRange.next());
                        }
                        d.setValidRange(newDescriptorRange);
                    }
                }
                Iterator ats = d.getAttributes();
                while (ats.hasNext()) {
                    Attribute a = (Attribute) ats.next();
                    Interpolator magic = getInterpolatorForType(a
                            .getAttrConfig().getAttrType());
                    a.startAggregating();
                    try {
                        helpInterpolateAttribute(a, start, newSpan, magic);
                    } catch (InterpolationException e) {
                        log
                                .severe("Error while interpolating descriptors: "
                                        + e.getLocalizedMessage());
                        throw new RuntimeException(e);
                    } finally {
                        a.finishAggregating(true);
                    }
                }
            }
}
```
